# No mostrar una línea vacía al inicio
add_newline = false

# Diseño del prompt: Solo carpeta, Git y el símbolo de comando
format = """
$directory\
$git_branch\
$git_status\
$character
"""

[character]
# Símbolo clásico de MS-DOS
success_symbol = "[>](bold white) "
error_symbol = "[>](bold red) "

[directory]
# Estilo de barra de título de Windows 95 (Fondo azul marino, texto blanco)
style = "fg:white bg:#000080"
format = "[ $path ]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
# Símbolo clásico y color gris claro (VGA)
symbol = "± "
style = "bold #C0C0C0"
format = "[$symbol$branch]($style) "

[git_status]
# Mantenemos el rojo para cuando hay cambios sin guardar
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

# Desactivamos explícitamente el módulo de Python/Conda
[python]
disabled = true
