add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character
"""

[character]
success_symbol = "[>](bold white) "
error_symbol = "[>](bold red) "

[directory]
style = "fg:white bg:#000080"
format = "[ $path ]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "± "
style = "bold #C0C0C0"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

[python]
disabled = true
